AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31
Description: >
  lambda-alone

  Sample SAM Template for lambda-alone

Globals:
  Function:
    Timeout: 5

Resources:
  Function:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: "lambda-alone"
      CodeUri: ./lambda-alone
      Handler: app.lambda_handler
      Runtime: python3.9
      Architectures:
        - arm64

Outputs:
  HelloWorldFunction:
    Description: "Lambda Function ARN"
    Value: !GetAtt Function.Arn
  HelloWorldFunctionIamRole:
    Description: "Implicit IAM Role created for function"
    Value: !GetAtt FunctionRole.Arn
